#!/bin/sh
echo Installing Graphical
yaourt --needed --noconfirm -S xorg xorg-xinit lxdm \
i3-gaps-git i3status i3lock python2 python2-imaging xpyb adobe-source-code-pro-fonts rofi feh \
firefox engrampa thunar thunar-volman thunar-shares-plugin