#!/bin/bash
command -v yaourt >/dev/null 2>&1 || { 
    echo Updating repos...
    sudo pacman -Syy
    echo Installing dependencies fakeroot and base-devel...
    sudo pacman --needed --noconfirm base-devel fakeroot wget git
    
    mkdir /tmp/install_yaourt
    cd /tmp/install_yaourt
    echo Downloading package-query...
    git clone https://aur.archlinux.org/package-query.git
    cd package-query
    makepkg -sri
    cd ..
    echo package-query installed...
    
    echo Downloading yaourt...
    mkdir yaourt
    cd yaourt
    curl https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=yaourt >PKGBUILD
    makepkg -s -f
    sudo pacman -U --noconfirm yaourt-*-*.pkg.tar.xz
    cd ..
    echo yaourt installed...
    echo Done.
}
